name: Build Linux ARM64 Executable

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    container:
      image: debian:bookworm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-venv python3-dev python3-pip \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Set up Python virtual environment and install Python packages
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Build with PyInstaller
        run: |
          . venv/bin/activate
          pyinstaller --onefile --name mygame_app main.py

      - name: Prepare artifact structure
        run: |
          mkdir -p artifact/mygame
          mv dist/mygame_app artifact/mygame/
          cp myGame.sh artifact/
          cp mygame.gptk artifact/mygame/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_linux_arm64
          path: artifact/
